version: '3'

services:
  app:
    build: .
    image: celinegaly/fastapi:latest
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: celinegaly/postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"